<template>
  <div class="content">
    <h3>RGB({{ selectedColor }}) Color Game</h3>
    <div class="header">
      <button @click="easyMode">Easy</button>
      <button @click="hardMode">Hard</button>
    </div>

    <ColorCards :colorCards="colorCards" :colors="colors"></ColorCards>

  </div>
</template>

<script>
import ColorCards from './ColorCards';

export default {
  name: 'ColorGame',
  data() {
    return {
      numColorCards: 6,
      randColor: null,
      colors: null,
      colorCards: null,
      selectedColor: null
    }
  },
  components: {
    ColorCards
  },
  methods: {
    // we're doing a few things here: we're grabbing all of the colorCards and also using the array from the randColorCards method. First, we're looping over all of the colorCards. We then are looking to see how many items the array contains. If there are items in the array, it will set display:block on the colorCards based upon the numColorCards defined in the button click events (easyGame, hardGame)
    setupColorCards() {
      this.colors = this.randColorCards(this.numColorCards);

      for (let i = 0; i < this.colorCards.length; i++) {
        this.colorCards[i].style.backgroundColor = this.colors[i];

        if(this.colors[i]) {
          this.colorCards[i].style.display = 'block';
        } else {
          this.colorCards[i].style.display = 'none';
        }
      }
    },
    // when clicked the easy mode button, we define the number of color cards to 3 and call the setupColor method 
    easyMode() {
        this.numColorCards = 3;
        this.setupColorCards();
    },
    /* when clicked the easy mode button, we define the number of color cards to 3 and call the setupColor
    method */
    hardMode() {
        this.numColorCards = 6;
        this.setupColorCards();
    },
    // based upon which game mode (easy - 3 squares || hard - 6 squares), this method pushes a random color generated by the randomColor method below based upon the defined number of squares into an array and returns that array so we can use it in the setupColorCards method defined above.
    randColorCards(num) {
      let arr = [];
      for (let i = 0; i < num; i++) {
        arr.push(this.randomColor()); 
      }
      return arr;
    },
    randomColor() {
      let r = Math.floor(Math.random() * 256);
      let g = Math.floor(Math.random() * 256);
      let b = Math.floor(Math.random() * 256);
      
      this.randColor = `rgb(${r},${g},${b})`;

      return this.randColor;
    }
  },
  mounted() {
    /* defines colorCards when the component mounts (loads). Prior to this, the array of color-cards wasn't created until the user clicked a game mode button */
    this.colorCards = document.querySelectorAll(".color-card");
    // the randColorCards method is being invoked and passing the inital state of numColorCards (6) to generate an array with 6 random rgb colors
    this.colors = this.randColorCards(this.numColorCards);
    //looping over all of the colorCards (6 on init) and assigning a randomly generated rgb color array to each colorCard
    for (let i = 0; i < this.colorCards.length; i++) {
      this.colorCards[i].style.backgroundColor = this.colors[i];
    }
  }
}
</script>

<style>
  .content {
    animation: fadeIn 1.2s;
  }
  .header {
    margin-bottom: 20px;
  }
  .hide {
    display: none;
  }
  .fadeOut {
    animation: fadeOut .5s;
    display: none;
  }
  .fadeIn {
    animation: fadeIn .5s;
    display: block;
  }
</style>

