<template>
  <div class="content">

    <div v-if="currentGame" class="game-mode">
      <p>Select the game mode: </p>
      <button @click="easyMode">Easy</button>
      <button @click="hardMode">Hard</button>
     </div>

    <div class="game-info">
      <p><strong>{{ gameMsg }}</strong></p>
      <button v-if="resetGame" @click="reset">Play Again?</button>
      <h3>{{ selectedColorUppercase }}</h3>
    </div>

    <ColorCards @user-guess="guess" :colorCards="colorCards" :colorArr="colorArr"></ColorCards>

  </div>
</template>

<script>
import ColorCards from './ColorCards';

export default {
  name: 'ColorGame',
  data() {
    return {
      numColorCards: 6,
      randColor: null,
      colors: null,
      colorCards: null,
      colorArr: null,
      selectedColor: '',
      gameMsg: "What color card matches the below RGB code?",
      resetGame: false,
      currentGame: true
    }
  },
  components: {
    ColorCards
  },
  computed: {
    selectedColorUppercase() {
      return this.selectedColor.toUpperCase();
    }
  },
  methods: {
    // we're doing a few things here: we're grabbing all of the colorCards and also using the array from the randColorCards method. First, we're looping over all of the colorCards. We then are looking to see how many items the array contains. If there are items in the array, it will set display:block on the colorCards based upon the numColorCards defined in the button click events (easyGame, hardGame)
    setupColorCards() {
      this.colors = this.randColorCards(this.numColorCards);

      for (let i = 0; i < this.colorCards.length; i++) {
        this.colorCards[i].style.backgroundColor = this.colors[i];

        if(this.colors[i]) {
          this.colorCards[i].style.display = 'block';
        } else {
          this.colorCards[i].style.display = 'none';
        }
      }
      this.randomArrColor();
    },
    // when clicked the easy mode button, we define the number of color cards to 3 and call the setupColor method 
    easyMode() {
      this.numColorCards = 3;
      this.setupColorCards();
    },
    /* when clicked the easy mode button, we define the number of color cards to 3 and call the setupColor
    method */
    hardMode() {
      this.numColorCards = 6;
      this.setupColorCards();
    },
    reset() {
      this.numColorCards = 6;
      this.resetGame = false;
      this.currentGame = true;
      this.gameMsg = "What color card matches the below RGB code?";
      this.setupColorCards();
      
    },
    randomArrColor() {
      this.randArrItem = (Math.floor(Math.random() * this.colorArr.length));
      this.selectedColor = this.colorArr[this.randArrItem]

      return this.setupColorCards; 
    },
    // based upon which game mode (easy - 3 squares || hard - 6 squares), this method pushes a random color generated by the randomColor method below based upon the defined number of squares into an array and returns that array so we can use it in the setupColorCards method defined above.
    randColorCards(num) {
      this.colorArr = [];
      for (let i = 0; i < num; i++) {
        this.colorArr.push(this.randomColor()); 
      }
      return this.colorArr;
    },
    // method that generates a random rgb color
    randomColor() {
      let r = Math.floor(Math.random() * 256);
      let g = Math.floor(Math.random() * 256);
      let b = Math.floor(Math.random() * 256);
      
      this.randColor = `rgb(${r}, ${g}, ${b})`;

      return this.randColor;
    },
    guess(bgColor) {
      this.randArrItem = bgColor.style.backgroundColor;
      let selectedColorLC = this.selectedColor.toLowerCase();
      
      if (this.randArrItem == selectedColorLC) {
        this.gameMsg = 'You Won!'

        this.colorCards.forEach((e) => {
          e.style.backgroundColor = this.randArrItem;
        });

        this.resetGame = true;
        this.currentGame = false;

      } else {
        bgColor.style.backgroundColor = 'transparent';
        bgColor.style.boxShadow = 'none';
        this.gameMsg = 'Try again!'
      }
    }
  },
  mounted() {
    /* defines colorCards when the component mounts (loads). Prior to this, the array of color-cards wasn't created until the user clicked a game mode button */
    this.colorCards = document.querySelectorAll(".color-card");
    // the randColorCards method is being invoked and passing the inital state of numColorCards (6) to generate an array with 6 random rgb colors
    this.colors = this.randColorCards(this.numColorCards);
    // looping over all of the colorCards (6 on init) and assigning a randomly generated rgb color array to each colorCard
    for (let i = 0; i < this.colorCards.length; i++) {
      this.colorCards[i].style.backgroundColor = this.colors[i];
    }
    // running this method when the component mounts as opposed to running when one of the mode buttons are clicked
    this.randomArrColor();
  }
}
</script>

<style>
  .content {
    animation: fadeIn 1.2s;
  }
  .game-mode {
    margin-bottom: -2px;
    color: #262626;
    font-weight: 100;
    font-size: 14px;
    display: flex;
    flex-direction: row;
    justify-content: center;
  }
  button {
    padding: 5px 20px;
    margin: 10px;
    background-color: #fff;
    background: #fff;
    border-color: #e7e7e7;
    cursor: pointer;
    outline: none;
  }
  .game-info h3 {
    font-weight: 400;
  }
  .hide {
    display: none;
  }
  .fadeOut {
    animation: fadeOut .5s;
    display: none;
  }
  .fadeIn {
    animation: fadeIn .5s;
    display: block;
  }
</style>

